FROM node:20-slim
RUN --mount=type=cache,target=/root/.npm \
    npm install -g pnpm@9
WORKDIR /app

COPY package.json pnpm-lock.yaml tsconfig.json ./
RUN pnpm install

COPY . .

EXPOSE 3000

ENV PORT=3000
CMD pnpm dev
